### ISSUE TITLE
Website roadmap

### ISSUE THREAD

**Issue by aays** [utm-coders/studyGroup#2]
- [x] Events section
    - [x] Update room + directions
    - [x] Update with details of first four events
        - [x] Add links to lesson content in event issues (when available)
    - [x] Add UTM coffee and codes ([see here](https://github.com/utm-coders/studyGroup/blob/gh-pages/_data/coffee-code.yml))
    - [x] Remove reference to past events from section header.
    - [x] Remove events calendar section from website - unless we're keeping this? 
- [x] Come say hi section
    - [x] Change email list link to listserv subscription link
    - [x] (Can we get a listserv for these??)
- [x] Centre "Want tp be notified" section
- [x] Contributors section
    - [x] Change 'Executive council' to something like 'Primary contributors'? Since we're not technically a student group ourselves
    - [x] Fix column spacing in above section (currently set to three columns)
    - [x] Clear out downtown contributors section for now
- [x] Friends and resources section
    - [x] Add the downtown Coders group! And mention that they're a huge part of why this series of workshops exists
- [x] Lesson content tab
    - [x] We might want to clear this out and add links to our own material as it's made, since for the most part we'll be creating new lessons as we go
- [x] Change link to Youtube on "Lesson content" page
- [x] Write brief README [here](https://github.com/utm-coders/Events/blob/master/README.md)

Anything else I'm missing?

**Comment by James-S-Santangelo** [comment]
Re: listserv. We probably could get one if we wanted to but because we are only doing this in the bio department at present it may not be worth it. If we expand to other departments then we should definitely consider this.

**Comment by James-S-Santangelo** [comment]
@aays Minor updates to issues list. Chipping away at this now.
